### PR TITLE
perf: optimize performance by not checking chars if we have one already

### PR DESCRIPTION
**Pull request by scastlara**
Maybe I misunderstood something, if so please feel free to just close!

But after inspection I noticed we are checking ALL characters in every word, no matter what.

From the tests:

For the sentence `first ok why` we check:
- `f`, for which we know there is only one occurrence.
- then `i`
- then `r`
- then `s`
- then `t`
- then `o` (for `ok`)
- then `k`
- then `w` (for `why`)
- then `h`
- then `y`

With this PR, after we know we have a single occurrence, we stop checking characters of that word. So we would stop at `f`.

- `f`, for which there is only one occurence
    > we don't check any other char for the word `first` since we know `f` is enough.
- then `o`
    > we don't check any other char for the word `ok` since we know `o` is enough.
- then `w`
    > we don't check any other char for the word `why` since we know `w` is enough.

image

Relates to #2

### CODE REVIEW

**Comment by scastlara** [comment]
The current behavior of the `master` branch has freq == 1 when there is a single occurence in the entire line, see with these console.logs:

```
at CharHighlighter.getCharColoring (CharHighlighter.ts:87:15)

    word: first, char: f, freq: 1

    word: first, char: i, freq: 1

    word: first, char: r, freq: 1

    word: first, char: s, freq: 1

    word: first, char: t, freq: 1

    word: ok, char: o, freq: 1

    word: ok, char: k, freq: 1

    word: why, char: w, freq: 1

    word: why, char: h, freq: 1

    word: why, char: y, freq: 1
```

**Comment by magdyamr542** [comment]
Hi @scastlara , thanks for the great work. I will check it this week and test it and if it's fine i will merge it and deploy it.
I think you are right, the code currently does unnecessary work by checking all other characters.
It's old piece of code and even though i wrote it a couple of years back, i had difficulty to understand it myself looking at it now :D.

**Comment by scastlara** [comment]
Nice! Thank you! I will be out the next two weeks for holidays, so feel free to do whatever you want with the PR. Once I am back I will take a look to see if it requires further work or something :)

Thanks a lot for this extension! It is really great!

**Comment by magdyamr542** [comment]
Ok i deployed the new version `v0.0.7` of the extension now @scastlara . It should be faster due to:
1. your change. thanks a lot for that.
2. based on your change, i got rid of the debouncing functionality which always waited 200 ms or so before triggering the code execution if the cursor kept moving. Now that the code is faster, we don't need such an optimization.

Here is the difference:
**Before performance update (and with debouncing)**:
https://github.com/magdyamr542/vim-find-highlight/assets/55108505/8588df66-a935-4ae3-bbf9-87217d712185


**After performance update (without debouncing)**:
https://github.com/magdyamr542/vim-find-highlight/assets/55108505/e0a890e5-ed0c-42ce-81a5-8c17d496d1dd

**Pull request merged**
